name: chatty
description: "A chat built with flutter using Firebase Cloud Firestore"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^3.0.0
  google_fonts: ^6.1.0
  iconsax: ^0.0.8
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#00FFFFFF"
    theme_color: "#00FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/anim/
    - assets/images/
    - assets/icon/